---
title: "R for Data Science"
output: html_document
---

```{r}
install.packages("Rcpp")
library("tidyverse")
```

# Chapter 1: Data Visualization with ggplot2

```{r}
mpg
```

```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x = displ, y = hwy))
```

```{r}
# 1. Run ggplot(data = mpg). What do you see?
ggplot(data = mpg)
```

Is jut a gray rectangle.

```{r}
# 2. How many rows are in mtcars? How many columns?
nrow(mtcars)
ncol(mtcars)
```

mtcars has 32 rows and 11 columns.

```{r}
# 3. What does the drv variable describe? Read the help for ?mpg to find out.
?mpg
```

The traction of the car, f if is a front-wheel drive,
r if is a rear-wheel drive, and 4 for a 4wd.

```{r}
# 4. Make a scatterplot of hwy versus cyl.
ggplot(data = mpg) +
  geom_point(mapping = aes(x = hwy, y = cyl))
```

```{r}
# 5. What happens if you make a scatterplot of class versus drv? Why is the plot not useful?
ggplot(data = mpg) +
  geom_point(mapping = aes(x = class, y = drv))
```

Class and drv don't contain numerical data, they have catergorical data. It just tells where both categories meet. 

```{r}
# github test
```

